config/routes.rb
Rails.application.routes.draw do
  resources :secrets do
    resources :comments
  end

  resources :comments do
    resources :comments
  end

  devise_for :users, controllers: { registrations: "registrations"}

  authenticated do
    root "secrets#index", as: "authenticated_root"
  end

  unauthenticated do 
    root "home#index"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  validates :body, presence: true
end

app/models/secret.rb
class Secret < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
  validates :title, presence: true, length: {in: 5..40}
  validates :body, presence: true, length: {in: 5..250}
  

  def self.remove(id)
    find(id).destroy
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :username, uniqueness: true, presence: true, length: {minimum: 5}

  has_many :secrets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: :show
  before_action :find_commentable

  def show
  end

  def new
    @comment = @commentable.comments.build
  end

  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.user_id = current_user.id
    respond_to do |format|
      if @comment.save
        @secret = get_secret() 
        flash.now[:notice] = "Comment posted"
        format.js { @secret } 
      else
        flash.now[:alert] = "Error posting comment"
        format.js { render json: @comment.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      redirect_to find_top_post(@comment), notice: "Comment has been updated"
    else
      redirect_to find_top_post(@comment), notice: "An error occured while editting your comment."
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @secret = get_secret()
    @comment.destroy
    respond_to do |format|
      flash.now[:notice] = "Sucessfully removed post"
      format.js { @secret }
    end
  end


  private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_commentable
      if params[:secret_id]
        @commentable = Secret.find_by_id(params[:secret_id])
      elsif params[:comment_id]
        @commentable = Comment.find_by_id(params[:comment_id])
      end
    end

    def get_secret
      Secret.find_by_id(params[:secret_id]) ||
          find_top_post(Comment.find(params[:comment_id]))
    end

    def find_top_post(comment)
      if comment.commentable_type == "Secret"
        return Secret.find_by_id!(comment.commentable_id)
      end
      find_top_post(Comment.find_by_id!(comment.commentable_id))
    end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
  
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
  
end

app/controllers/secrets_controller.rb
class SecretsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  # after_action :remove, only: [:create]
  def show
    @secret = Secret.find(params[:id])
    session[:return] = request.referer
  end

  def index
    @secret = Secret.all
  end

  def new
    @secret = current_user.secrets.build
    respond_to do |format|
      format.js
    end
  end

  def create
    @secret = current_user.secrets.build(secret_params)

    respond_to do |format|
      if @secret.save
        flash.now[:notice] = "Secret has been posted"
        format.js { @secret = Secret.all }
      else
        flash.now[:alert] = "Please ensure title and body length is 5 characters minimum"
        format.json { render json: @secret.errors.full_messages, status: :unprocessable_entity}
        format.js
      end
    end

  end

  def edit
    @secret = current_user.secrets.find(params[:id])
  end

  def update
    @secret = current_user.secrets.find(params[:id])
    if @secret.update(secret_params)
      redirect_to root_path, notice: "Your secret has been updated"
    else
      render :edit, notice: "Invalid secret update"
    end
  end

  def destroy
    @secret = Secret.find(params[:id])
    @secret.destroy
    redirect_to root_path, notice: "Secret successfully removed."
  end

  private

  def secret_params
    params.require(:secret).permit(:title, :body)
  end

  def remove
    Secret.delay(queue: "removable", priority: 0, run_at: 10.seconds.from_now).remove(Secret.find(params[:id]))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/secrets_helper.rb
module SecretsHelper
end

app/views/comments/_comments.html.erb
<% commentable.comments.each do |comment|%>

  <div class="container-fluid bg-dark text-wrap text-light rounded my-1 pe-0"id="comment<%comment.id%>">
    
    <div class="container d-flex justify-content-end position-relative end-0 p-0">
      <%= render "shared/comment_header", comment: comment%>
    </div>

    <p class="lead text-wrap text-break pt-2">
        <%= comment.body%>
    </p>
    <div class="container d-flex justify-content-end">
      <% if user_signed_in? %>
        <% 
        linked_path = new_comment_comment_url(comment_id: comment.id, format: :js)
        bool = true %>
      <% else %>
         <% 
          linked_path = new_user_session_path
          bool = false
         %>
      <% end %>

      <%= link_to "Reply", linked_path,
        remote: bool,
        class: "btn btn-primary btn-sm mb-3"%>
    </div>
  </div>
  <div class="container-fluid text-light rounded my-2 d-flex flex-column justify-content-end pe-0">
    <%= render "comments/comments", commentable: comment %>
  </div>

<% end %>

app/views/comments/_modal.html.erb
<%= form_with(model: [@commentable, @comment], remote: true, local: false) do |f|%>
  <div class="modal-header">
    <h2 class="modal-title fw-bold">
      Comment
    </h2>
  </div>
  <div class="modal-body">
    <%= f.text_area :body, required: true,
      class: "container-fluid"%>
  </div>
  <div class="modal-footer d-flex">
    <%= f.submit "Reply",
      class: "btn btn-primary align-self-end m-1"%>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#flash").html("<%= j (render "shared/flash_messages")%>")
<% if !flash.now[:alert]%>
  $("#comment-stream").html("<%= j (render "comments", commentable: @secret)%>")
<% end %>
$("#modal-comment").modal("hide")

app/views/comments/destroy.js.erb
$("#flash").html("<%= j (render "shared/flash_messages")%>")
<% if !flash.now[:alert]%>
  $("#comment-stream").html("<%= j (render "comments", commentable: @secret)%>")
<% end %>
$("#modal-delete").modal("hide")

app/views/comments/edit.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center text-light mt-3">
  <%= form_with model: @comment do |f|%>
    <div class="container d-flex flex-column">
     <%= f.label :body,
       class: "fs-4 fw-bold m-2"%>
     <%= f.text_area :body, required: true%>
    </div>
    <div class="container ">
      <%= f.submit class: "btn btn-sm btn-primary mt-3"%>
    </div>
  <% end %>
</div>

app/views/comments/new.js.erb
$("#modal-comment").find(".modal-content").html("<%= j (render "modal")%>");
$("#modal-comment").modal("show");

app/views/home/index.html.erb
<div class="container container-bg mt-3">
  <div class="row g-3 mb-4 mb-md-1">
    <div class="col-md">
        <%= image_tag "svg_images/add_post.svg", class:"container container-bg" %>
    </div>
    <div class="col-md d-flex flex-column justify-content-evenly">
      <p class="text-light fs-3 fw-bold">Post</p>
      <p class="text-light align-self-center lead">Create posts to share with other members. Posts will stay up for 24 hours.</p>
    </div>
  </div>
  <br/>
  <div class="row g-3 mb-4 mb-md-1">
    <div class="col-md order-md-2">
      <%= image_tag "svg_images/anonymous.svg", class: "container container-bg-sm"%>
    </div>
    <div class="col-md d-flex flex-column justify-content-evenly order-md-1">
      <p class="text-light fs-3 fw-bold">Stay Anonymous</p>
      <p class="text-light align-self-center lead">
        The author of posts will only be visible to other members.<strong> Outsiders wont be able to see who made the post,</strong> but can still see the post.
      </p>
    </div>
  </div>
  <div class="row g-3 mb-4 mb-md-1">
    <div class="col-md">
      <%= image_tag "svg_images/mobile_feed.svg", class: "container container-bg"%>
    </div>
    <div class="col-md d-flex flex-column justify-content-evenly">
      <p class="text-light fs-3 fw-bold">Explore</p>
      <p class="text-light lead">
        Browse posts from users, write comments, and like your favourite posts.
      </p>
      <%= link_to "Browse Secrets Now", secrets_url,
        class: "btn btn-tert text-light hover"%>
    </div>
  </div>
  <div class="container container-bg text-center my-3 d-sm-none">
    <%= link_to "Join the Club", new_user_registration_path,
      class: "btn btn-lg btn-secondary"%>
    <%= link_to "Login", new_user_session_path, 
      class: "btn btn-lg btn-sec"%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
        <div class="container-fluid">
          <%= link_to "Members Only", root_path,
            class: "fs-4 text-light btn navbar-brand"%>

          <button class="navbar-toggler" type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapsable" 
            aria-controls="collapsable" 
            aria-expanded="false" 
            aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="collapsable">
            <% if current_user%>
              <%= render "secrets/logged_in"%>
            <% else %>
              <%= render "secrets/not_logged_in"%>
            <% end %>

          </div>
        </div>
      </nav>
      <div class="container-fluid px-0 zindex-alert position-absolute top-10 " id="flash">
        <%= render "shared/flash_messages"%>
      </div>

    <%= yield %>
  </body>
</html>

app/views/secrets/_comment_confirmation.html.erb
<div class="modal-header text-dark">
  <h5 class="modal-title">Delete Post</h5>
</div>
<div class="modal-body">
  <div class="container text-dark">
    <p class="lead">
      Are you sure you want to delete this comment? 
    </p>
  </div>
</div>
<div class="modal-footer">
  <button type="button" 
  class="btn btn-primary fw-bold text-light"
  data-bs-dismiss="modal"
  aria-label="Cancel">Cancel</button>

  <% if comment.commentable_type == "Secret"%>
  <% linked_path = secret_comment_url(id: comment.id, secret_id: comment.commentable_id)%>
  <% else %>
  <% linked_path = comment_comment_url(id: comment.id, comment_id: comment.commentable_id)%>
  <% end %>
  <%= link_to "Delete", linked_path, 
  method: :delete,
  remote: true,
  class: "btn btn-danger",
  "data-bs-dismiss" => "modal" %>
</div>

app/views/secrets/_confirmation.html.erb
<div class="modal-header">
  <h5 class="modal-title">Delete Post</h5>
</div>
<div class="modal-body">
  <div class="container">
    <p class="lead">
      Are you sure you want to delete this secret? 
    </p>
  </div>
</div>
<div class="modal-footer">
  <button type="button" 
  class="btn btn-primary fw-bold text-light"
  data-bs-dismiss="modal"
  aria-label="Cancel">Cancel</button>
  <%= link_to "Delete", secret, 
  method: :delete,
  class: "btn btn-danger",
  "data-bs-dismiss" => "modal" %>
</div>

app/views/secrets/_empty.html.erb
<div class="container text-center mt-4 text-light">
  <h1 class="fs-2 fw-bold">
    Secrets never last...
  </h1>
  <p class="lead"> There are no secrets posted at the moment.</p>
  <% if !current_user %>
    <p class="lead"> Join today and share a secret ! </p>
    <%= link_to "Login", new_user_session_path,
      class: "btn btn-sec hover" %>
  <% else %>
    <p class="lead"> Got a secret to share ? </p>
    <%= link_to "Share Secret", new_secret_url,
      remote: true,
      "data-bs-toggle" => "modal",
      "data-bs-target" => "#modal-window",
      class: "btn btn-tert hover"%>
  <% end %>
</div>

app/views/secrets/_feed.html.erb
<% @secret.reverse.each do |secret|%>

  <div class="container d-flex flex-column justify-content-center mt-2 border rounded bg-light">

    <div class="container d-flex justify-content-end position-relative end-0 p-0">
      <%= render "shared/post_header", secret: secret%>
    </div>
    <div class="container border-bottom border-success d-flex justify-content-between title px-0">
      <%= link_to secret_url(secret.id) do%>
        <h3 class="fs-2 fw-bold hover">
          <%= secret.title %>
        </h3>
      <% end %>

    </div>
    <div class="container px-0">
      <p class="py-2 px-0"><%= secret.body %></p>
    </div>
  </div>
<% end %>

app/views/secrets/_form.html.erb
  <%= form_with(model: @secret,local: false, remote: true) do |f| %>
<div class="modal-header">
  <h5 class="modal-title">Create Secret</h5>
  <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
</div>
<div class="modal-body">
  <div class="container d-flex flex-column justify-content-center">

      <div class="container d-flex flex-column">
        <%= f.label :title,
          class: "fs-4 fw-bold"%>
        <%= f.text_field :title,
         required: true, 
         id:"title_field" %>
      </div>
      <div class="container d-flex flex-column">
        <%= f.label :body,
          class: "fs-4 fw-bold"%>
        <%= f.text_area :body, required: true, id: "body_field" %>
      </div>
  </div>
</div>
  <div class="modal-footer container d-flex flex-column  align-items-end">
    <%= f.submit "Create Secret",
      class: "btn btn-primary btn-sm hover",
      id: "form-submit"%>
  </div>
    <% end %>

<%# 

Since the new and create actions are ajax calls, the jquery is 
not reloaded, and cannot find the submit button. Putting the
script in here solves that issue.

 %>
<script> 

$modal = $("#modal-window")
$("#form-submit").on("click", () =>{
  console.log("clicked")
  $submit = $("#form-submit")
  $title = $("#title_field").val()
  $body = $("#body_field").val()
  if (($title !== "") && ($body !== "")) {
    $modal.modal("hide")
  }

})

</script>

app/views/secrets/_logged_in.html.erb
<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
  <li class="nav-item m-1 d-none d-md-inline">
    <div class="container">
      <%= link_to "Share Secret", new_secret_url,
        remote: true,
        "data-bs-toggle" => "modal",
        "data-bs-target" => "#modal-window",
        class: "btn text-light btn-main hover"%>
    </div>
  </li>
  <li class="nav-item m-1 d-none d-md-inline">
    <div class="container">
      <%= link_to "Logout", destroy_user_session_path,
        method: :delete,
        class: "btn text-dark btn-sec hover" %>
    </div>
  </li>
  <li class="nav-item me-auto d-md-none">
    <div class="container">
      <%= link_to "Share Secret", new_secret_url,
        remote: true,
        "data-bs-toggle" => "modal",
        "data-bs-target" => "#modal-window",
        class: "btn text-light hover"%>
    </div>
  </li>
  <li class="nav-item me-auto d-md-none">
    <div class="container">
      <%= link_to "Logout", destroy_user_session_path,
        method: :delete,
        class: "btn text-light hover" %>
    </div>
  </li>
</ul> 

app/views/secrets/_not_logged_in.html.erb
<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
  <li class="nav-item m-1 d-none d-md-inline">
    <div class="container">
      <%= link_to "Sign Up", new_user_registration_path,
        class: "btn text-light btn-main hover"%>
    </div>
  </li>
  <li class="nav-item m-1 d-none d-md-inline">
    <div class="container">
      <%= link_to "Login", new_user_session_path,
        class: "btn text-dark btn-sec hover" %>
    </div>
  </li>
  <li class="nav-item me-auto d-md-none">
    <div class="container">
      <%= link_to "Sign Up", new_user_registration_path,
        class: "btn text-light hover"%>
    </div>
  </li>
  <li class="nav-item me-auto d-md-none">
    <div class="container">
      <%= link_to "Login", new_user_session_path,
        class: "btn text-light hover" %>
    </div>
  </li>
</ul> 

app/views/secrets/create.js.erb
$("#flash").html("<%= j (render "shared/flash_messages")%>")
<% if !flash.now[:alert] %>
  $("#post-feed").html("<%= j (render "feed") %>");
<% end %>

app/views/secrets/edit.html.erb
<div class="container d-flex flex-column justify-content-center align-items-center text-light mt-3">
  <%= form_with model: @secret do |f|%>
    <div class="container d-flex flex-column">
    <%= f.label :title,
      class: "fs-4 fw-bold m-2"%>
    <%= f.text_field :title,
      required: true, 
      id:"title_field" %>
    </div>
    <div class="container d-flex flex-column">
     <%= f.label :body,
       class: "fs-4 fw-bold m-2"%>
     <%= f.text_area :body, required: true, id: "body_field" %>
    </div>
    <div class="container ">
      <%= f.submit class: "btn btn-sm btn-primary mt-3"%>
    </div>
  <% end %>
</div>

app/views/secrets/index.html.erb
<div class="modal fade" id="modal-window" tabindex="-1">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

<div class="container container-bg mt-2">

  <div class="row">
    <div class="col d-none d-lg-block">
      
    </div>
    <div class="col-12 col-lg-6 mb-3" id="post-feed">
      <% if @secret.is_a?(Enumerable) && @secret.empty? %>
        <%= render "empty"%>
      <% else %>
        <%= render "feed" %>
      <% end %>
    </div>
    <div class="col d-none d-lg-block">

    </div>
  </div>

</div>

app/views/secrets/new.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render "form") %>");
$("#modal-window").modal();

app/views/secrets/show.html.erb
<div class="modal fade" id="modal-comment" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content"></div>
  </div>
</div>

<div class="container-fluid d-flex flex-column justify-content-center mt-4 p2" style="min-width: 50vw;max-width: 40rem">

  <div class="container d-flex flex-column bg-light rounded">
    <div class="container d-flex justify-content-end position-relative end-0 p-0">
      <%= render "shared/post_header", secret: @secret%>
    </div>
    <h2 class="fw-bold">
      <%= @secret.title %>
    </h2>
    <hr>
    <p class="lead ps-2">
      <%= @secret.body %>
    </p>
    <% if user_signed_in? %>
      <% 
      linked_path = new_secret_comment_path(secret_id: @secret.id,format: :js)
      bool = true %>
    <% else %>
      <% 
      linked_path = new_user_session_path
      bool = false 
      %>
    <% end %>
      <%= link_to "Comment", linked_path,
        remote: bool,
        class: "btn btn-sec align-self-end w-20 p-2 m-2 hover"%>
    <div class="container-fluid px-0" id="comment-stream">
      <%= render "comments/comments", commentable: @secret%>
    </div>
  </div>


  <div class="container mt-3 p-0">
    <%= link_to "Back", secrets_url, class: "btn btn-sec mb-3" %>
  </div>
</div>

app/views/shared/_comment_header.html.erb
<% if user_signed_in? %>

    <div class="container-fluid my-auto px-0">
      <p class="m-0">From: <%= comment.user.username %></p>
    </div>

    <% if current_user == comment.user %>
      <%= link_to edit_comment_url(comment.id),
        class: "btn btn-link pe-0" do %>
        <span class="icon"><i class="bi bi-pencil" aria-hidden="true"></i></span>
      <% end %>
      <button class="btn btn-link "
        type="button"
        data-bs-toggle="modal"
        data-bs-target="#modal-delete<%= comment.id%>">
        <span class="icon"><i class="bi bi-trash" aria-hidden="true"></i></span>
      </button>
    

    <div class="modal fade" id="modal-delete<%= comment.id%>" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content"> <%= render "secrets/comment_confirmation", comment: comment%> </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash[:notice] || flash.now[:notice]%>
  <div class="container-fluid alert alert-primary fw-bold mx-0 text-center zindex-alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] || flash.now[:alert] %>
  <div class="container-fluid alert alert-danger fw-bold mx-0 text-center zindex-alert">
    <%= flash[:alert] %>
  </div>
<% end %>

<script>
  $(".alert").fadeOut(3750)
</script>

app/views/shared/_post_header.html.erb
<% if user_signed_in? %>

  <div class="container d-flex justify-content-end position-relative end-0 p-0">
    <div class="container-fluid my-auto px-0">
      <p class="m-0">From: <%= secret.user.username %></p>
    </div>

    <% if current_user == secret.user %>
      <%= link_to edit_secret_url(secret.id),
        class: "btn btn-link pe-0" do %>
        <span class="icon"><i class="bi bi-pencil" aria-hidden="true"></i></span>
      <% end %>
      <button class="btn btn-link "
        type="button"
        data-bs-toggle="modal"
        data-bs-target="#modal-delete<%= secret.id%>">
        <span class="icon"><i class="bi bi-trash" aria-hidden="true"></i></span>
      </button>
    

    <div class="modal fade" id="modal-delete<%= secret.id%>" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content"> <%= render "confirmation", secret: secret%> </div>
      </div>
    </div>
  </div>
  <% end %>
<% end %>